"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Backpack_1 = require("./src/Backpack");
var Car_1 = require("./src/Car");
var Computer_1 = require("./src/Computer");
var Person_1 = require("./src/Person");
var backPack = new Backpack_1.Backpack();
var car = new Car_1.Car();
var computer = new Computer_1.Computer();
var person = new Person_1.Person();
backPack.setShoeWeight(1);
backPack.setShirtWeight(3);
backPack.setPantsWeight(2);
console.log(backPack.getTotalWeight());
car.model = 'tesla';
car.numSeats = 6;
car.addSeats(3);
console.log(car.numSeats);
computer.speed = 20;
computer.turnOn(200);
computer.cpu = 'intel';
computer.runSpeedTest(200);
computer.upGradeSpeed(20);
person.gender = "f";
person.weight = 80;
person.name = "Donald Trump";
person.checkScale();
person.feedUntilFull("cholent");
person.feed("cholent");
person.checkScale();
// person.feedUntilFull("cholent");
// person.checkScale(40);
